name: Python Test

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Repository indir
        uses: actions/checkout@v4

      - name: Python kontrol
        run: |
          python --version
          pip --version
          python -c "import requests; print('REQUESTS OK')"
